/*
 * tags — layer 1b: what each {@tag} MEANS.
 *
 * parseMarkup.ts gives us {name, args}. This turns that into a description of
 * what should appear on screen, without deciding how it looks. The React
 * layer reads `kind` and styles accordingly.
 *
 * The tag list is taken from MARKUP-INVENTORY.md — generated by
 * `npm run survey-markup` from the actual contents of data/, not from the
 * illustrative examples in NOTES.md. Every `{@…}` tag that occurs in our data
 * is handled here. The inventory's `{#itemEntry}` and `{{…}}` rows are a
 * different sigil this layer never sees — `{#itemEntry}` is resolved before
 * rendering (src/inventory/itemEntryResolver.ts).
 *
 * Display semantics follow js/render.js in the 5etools source
 * (data-source/…/js/render.js, class Renderer.tag, ~line 5280 onward).
 * We reimplement, we do not copy: 5etools builds DOM strings and hyperlinks,
 * we build React and — for now — plain styled text.
 */

import type { MarkupTagNode } from './parseMarkup'
import { unknownTagWarnings } from './warnings'

/* ============================================================================
 * SECTION 1 — WHAT A RESOLVED TAG LOOKS LIKE
 * ==========================================================================*/

export type TagKind = 'emphasis' | 'reference' | 'value'

/**
 * A cross-reference target, preserved in full so that links can be added
 * later without touching the parser (PHASE1.md section D).
 *
 * `source` is deliberately NOT defaulted when blank. Per NOTES.md, a blank
 * source means the 2014 PHB rather than "the current book", and baking that
 * assumption in here would hide the distinction from whatever resolves these
 * references later.
 */
export interface TagReference {
	/** Category being pointed at: "spell", "item", "condition", … */
	category: string
	/** Entry name as written, e.g. "Fireball". */
	name: string
	/** Source book code, e.g. "XPHB". Empty string when the data omitted it. */
	source: string
	/** Every raw argument, for targets that need more than name+source
	 *  (classFeature carries class, level and source; quickref carries a
	 *  chapter index). */
	args: string[]
}

export interface ResolvedTag {
	kind: TagKind
	/** Tag name, e.g. "spell". Used as a CSS modifier by the React layer. */
	name: string
	/**
	 * The text to show. May itself contain markup — the component layer
	 * re-parses it, which is how nested tags are handled.
	 */
	display: string
	/** Present when kind === 'reference'. */
	reference?: TagReference
	/** Present when kind === 'emphasis'. */
	emphasis?: 'bold' | 'italic'
	/** True when the tag name is not in the table below. */
	isUnknown: boolean
}

/* ============================================================================
 * SECTION 2 — THE TAG TABLE
 * ==========================================================================*/

/*
 * Cross-reference tags.
 *
 * The value is the argument index holding an optional display-text override.
 * The general 5etools shape is `name|source|displayText`, but tags carrying
 * more identifying parts push the override further right — a class feature
 * needs name|class|classSource|level|source before it gets to display text.
 *
 * Rule applied uniformly: display = args[overrideIndex] || args[0].
 *
 * For `book`, `filter` and `5etools` the first argument IS the display text
 * and there is no override, so the index is 0 and the rule degrades to args[0]
 * (5etools calls these _TagPipedNoDisplayText).
 */
const REFERENCE_TAGS: Record<string, number> = {
	// name|source|displayText
	action: 2,
	class: 2,
	condition: 2,
	creature: 2,
	deck: 2,
	feat: 2,
	hazard: 2,
	item: 2,
	itemMastery: 2,
	itemProperty: 2,
	language: 2,
	object: 2,
	optfeature: 2,
	race: 2,
	sense: 2,
	skill: 2,
	spell: 2,
	status: 2,
	table: 2,
	variantrule: 2,

	// name|pantheon|source|displayText
	deity: 3,

	// name|className|classSource|subclassSource|displayText
	subclass: 4,
	// name|source|chapterIndex|headerIndex|displayText
	quickref: 4,

	// name|className|classSource|level|source|displayText
	classFeature: 5,

	// name|className|classSource|subclassShortName|subclassSource|level|source|displayText
	subclassFeature: 7,

	// displayText is the first argument; no override exists
	book: 0,
	filter: 0,
	'5etools': 0,
}

const EMPHASIS_TAGS: Record<string, 'bold' | 'italic'> = {
	b: 'bold',
	i: 'italic',
}

/** Formats a number with an explicit sign, as attack bonuses are written. */
function signed(raw: string): string {
	const asNumber = Number(raw)
	if (Number.isNaN(asNumber)) return raw
	return `${asNumber >= 0 ? '+' : ''}${asNumber}`
}

/*
 * Value tags — dice, DCs, percentages. These render as text, never as links.
 * Each function receives the raw argument list.
 */
const VALUE_TAGS: Record<string, (args: string[]) => string> = {
	// "{@damage 2d6}" -> "2d6". Semicolons separate alternatives and are
	// written as slashes: "1d8;1d10" -> "1d8/1d10" (versatile weapons).
	damage: (args) => args[1] || (args[0] ?? '').replace(/;/g, '/'),
	dice: (args) => args[1] || (args[0] ?? '').replace(/;/g, '/'),

	// "{@hit 5}" -> "+5"
	hit: (args) => args[1] || signed(args[0] ?? ''),

	// "{@dc 15}" -> "DC 15"
	dc: (args) => `DC ${args[1] || (args[0] ?? '')}`,

	// "{@chance 50}" -> "50 percent". The 4th and 5th arguments seen in
	// spells.json ("{@chance 25|||Random reading!|Regular reading}") are
	// success/failure flavour for an interactive roll, not display text.
	chance: (args) => args[1] || `${args[0] ?? ''} percent`,

	// "{@scaledamage 1d8|3,5,7,9|1d8}" -> "1d8"
	// Argument 2 is the amount added PER STEP of upcasting, which is what the
	// surrounding sentence is always talking about ("increases by …").
	scaledamage: (args) => args[4] || args[2] || '',
	scaledice: (args) => args[4] || args[2] || '',

	// "{@tip Die Size|Psionic Energy Die Size}" — argument 2 is hover help,
	// which we have nowhere to put, so only the visible text survives.
	tip: (args) => args[0] ?? '',

	// "{@recharge 5}" -> "(Recharge 5–6)"; a bare "{@recharge}" means 6, which
	// recharges on a 6 alone and so carries no range. The second argument
	// ("{@recharge 5|m}") is 5etools' roll-flavour flag, not display text.
	recharge: (args) => {
		const value = Number(args[0] || 6)
		if (Number.isNaN(value)) return `(Recharge ${args[0] ?? ''})`
		return `(Recharge ${value}${value < 6 ? '–6' : ''})`
	},
}

/* ----------------------------------------------------------------------------
 * Stat-block label tags.
 *
 * These introduce the text after them rather than naming a thing — the bold
 * lead-ins a 2024 stat block prints before an action's attack, hit, trigger or
 * save-outcome line. Their own arguments are consumed INTO the label (an
 * attack's "m" becomes "Melee", a save's "str" becomes "Strength"), so nothing
 * is carried on the element the way a cross-reference is.
 * -------------------------------------------------------------------------*/

const ABILITY_FULL_NAMES: Record<string, string> = {
	str: 'Strength',
	dex: 'Dexterity',
	con: 'Constitution',
	int: 'Intelligence',
	wis: 'Wisdom',
	cha: 'Charisma',
}

// Letter -> word, in the precedence order Renderer.attackTagToFull applies.
const ATTACK_TYPE_WORDS: ReadonlyArray<readonly [string, string]> = [
	['m', 'Melee '],
	['r', 'Ranged '],
	['g', 'Magical '],
	['a', 'Area '],
]
const ATTACK_METHOD_WORDS: ReadonlyArray<readonly [string, string]> = [
	['w', 'Weapon '],
	['s', 'Spell '],
	['p', 'Power '],
]

/**
 * "{@atkr m}" -> "Melee Attack Roll:", "{@atkr mw,rw}" -> "Melee or Ranged
 * Weapon Attack Roll:".
 *
 * Comma-separated groups share their trailing words: a letter already used by
 * a LATER group is dropped from the earlier ones, which is what turns
 * "mw,rw" into one "Weapon" rather than two.
 */
function attackTagToFull(raw: string, isRoll: boolean): string {
	const groups = raw
		.toLowerCase()
		.split(',')
		.map((part) => part.trim())
		.filter(Boolean)
		.map((part) => part.split(''))

	if (groups.length > 1) {
		const seen = new Set<string>(groups[groups.length - 1])
		for (let index = groups.length - 2; index >= 0; index--) {
			groups[index] = (groups[index] ?? []).filter((letter) => {
				const keep = !seen.has(letter)
				seen.add(letter)
				return keep
			})
		}
	}

	const parts = groups.map((letters) => {
		const type = ATTACK_TYPE_WORDS.find(([letter]) => letters.includes(letter))?.[1] ?? ''
		const method = ATTACK_METHOD_WORDS.find(([letter]) => letters.includes(letter))?.[1] ?? ''
		return `${type}${method}`
	})

	return `${parts.join(' or ')}Attack${isRoll ? ' Roll' : ''}:`
}

const ORDINAL_WORDS = [
	'First',
	'Second',
	'Third',
	'Fourth',
	'Fifth',
	'Sixth',
	'Seventh',
	'Eighth',
	'Ninth',
	'Tenth',
]

function ordinalWord(raw: string): string {
	const value = Number(raw)
	if (!Number.isInteger(value) || value < 1) return raw
	return ORDINAL_WORDS[value - 1] ?? `${value}th`
}

const LABEL_TAGS: Record<string, (args: string[]) => string> = {
	// "{@h}" -> "Hit: ". The trailing space is 5etools' own; the damage
	// sentence follows immediately after the tag.
	h: () => 'Hit: ',

	atkr: (args) => attackTagToFull(args[0] ?? '', true),

	// "{@actSave dex}" -> "Dexterity Saving Throw:"
	actSave: (args) => `${ABILITY_FULL_NAMES[args[0] ?? ''] ?? args[0] ?? ''} Saving Throw:`,
	actSaveSuccess: () => 'Success:',
	// An argument numbers the failure step ("{@actSaveFail 1}" -> "First
	// Failure:"), used by effects that worsen on a second failed save.
	actSaveFail: (args) => (args[0] ? `${ordinalWord(args[0])} Failure:` : 'Failure:'),

	actTrigger: () => 'Trigger:',
	// A dice-carrying response is written with a dash rather than a colon.
	actResponse: (args) => `Response${(args[0] ?? '').includes('d') ? '—' : ':'}`,
}

/* ============================================================================
 * SECTION 3 — UNKNOWN TAG REPORTING
 * ==========================================================================*/

/**
 * Clears the "already warned" record. Tests use this; nothing else should.
 */
export function resetUnknownTagWarnings(): void {
	unknownTagWarnings.reset()
}

/** The tag names seen so far that are not in the table. Exposed for tests. */
export function getUnknownTagsSeen(): string[] {
	return unknownTagWarnings.seen()
}

function warnOnce(name: string, raw: string): void {
	unknownTagWarnings.warn(
		name,
		`[markup] Unhandled 5etools tag {@${name}}. Rendering its text as-is. ` +
			`First seen in: ${raw}. ` +
			`If this tag now occurs in data/, add it to src/markup/tags.ts and ` +
			`re-run \`npm run survey-markup\`.`,
	)
}

/* ============================================================================
 * SECTION 4 — RESOLUTION
 * ==========================================================================*/

/**
 * Works out what a parsed tag should display.
 *
 * Never throws and never returns braces: an unrecognised tag degrades to its
 * first argument, which for essentially every 5etools tag is human-readable
 * text. A warning is logged once per distinct tag name, not once per
 * occurrence — otherwise a single spell list would flood the console.
 */
export function resolveTag(node: MarkupTagNode): ResolvedTag {
	const { name, args, raw } = node

	const emphasis = EMPHASIS_TAGS[name]
	if (emphasis) {
		return {
			kind: 'emphasis',
			name,
			display: args[0] ?? '',
			emphasis,
			isUnknown: false,
		}
	}

	const labelRenderer = LABEL_TAGS[name]
	if (labelRenderer) {
		return {
			kind: 'emphasis',
			name,
			display: labelRenderer(args),
			emphasis: 'bold',
			isUnknown: false,
		}
	}

	const valueRenderer = VALUE_TAGS[name]
	if (valueRenderer) {
		return {
			kind: 'value',
			name,
			display: valueRenderer(args),
			isUnknown: false,
		}
	}

	const overrideIndex = REFERENCE_TAGS[name]
	if (overrideIndex !== undefined) {
		return {
			kind: 'reference',
			name,
			display: args[overrideIndex] || args[0] || '',
			reference: {
				category: name,
				name: args[0] ?? '',
				source: args[1] ?? '',
				args,
			},
			isUnknown: false,
		}
	}

	warnOnce(name, raw)
	return {
		kind: 'value',
		name,
		display: args[0] ?? '',
		isUnknown: true,
	}
}

/** Every tag name this module handles. Used by the tests to prove coverage. */
export function getHandledTagNames(): string[] {
	return [
		...Object.keys(EMPHASIS_TAGS),
		...Object.keys(LABEL_TAGS),
		...Object.keys(VALUE_TAGS),
		...Object.keys(REFERENCE_TAGS),
	].sort()
}
