export { ResolvedEntries } from './ResolvedEntries'
export { loadResolverData } from './loadResolverData'
export { resolveRef } from './resolveRef'
export { scanRefs, distinctRefs } from './scanRefs'
export { buildExpansions } from './expandRefs'
export type { RefKind, RefOccurrence, ResolvedFeature, ResolverData } from './refTypes'
export type { Expansion } from './expandRefs'
